# init

name: init

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm
        run: |
          npm install @notionhq/client forever -g
          npm install forever -g
